author: artemave
description: "generate docker server and client certificates"
os: darwin linux windows
includes:
  - README.md
  - LICENSE
  - conf
  - templates
  - public
  - static
  - views
excludes:
  - \.git
script:
  - go get -v
  - go build
